<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefTbuSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Laki-laki (WHO)
            ['gender' => 'laki-laki', 'usia_bulan' => 0, 'median' => 49.88, 'sd' => 1.89],
            ['gender' => 'laki-laki', 'usia_bulan' => 1, 'median' => 54.72, 'sd' => 1.97],
            ['gender' => 'laki-laki', 'usia_bulan' => 2, 'median' => 58.42, 'sd' => 2.02],
            ['gender' => 'laki-laki', 'usia_bulan' => 3, 'median' => 61.43, 'sd' => 2.04],
            ['gender' => 'laki-laki', 'usia_bulan' => 4, 'median' => 63.90, 'sd' => 2.06],
            ['gender' => 'laki-laki', 'usia_bulan' => 5, 'median' => 65.91, 'sd' => 2.08],
            ['gender' => 'laki-laki', 'usia_bulan' => 6, 'median' => 67.62, 'sd' => 2.09],
            ['gender' => 'laki-laki', 'usia_bulan' => 7, 'median' => 69.17, 'sd' => 2.11],
            ['gender' => 'laki-laki', 'usia_bulan' => 8, 'median' => 70.60, 'sd' => 2.13],
            ['gender' => 'laki-laki', 'usia_bulan' => 9, 'median' => 72.01, 'sd' => 2.15],
            ['gender' => 'laki-laki', 'usia_bulan' => 10, 'median' => 73.28, 'sd' => 2.17],
            ['gender' => 'laki-laki', 'usia_bulan' => 11, 'median' => 74.54, 'sd' => 2.19],
            ['gender' => 'laki-laki', 'usia_bulan' => 12, 'median' => 75.70, 'sd' => 2.20],
            ['gender' => 'laki-laki', 'usia_bulan' => 13, 'median' => 76.85, 'sd' => 2.21],
            ['gender' => 'laki-laki', 'usia_bulan' => 14, 'median' => 77.98, 'sd' => 2.22],
            ['gender' => 'laki-laki', 'usia_bulan' => 15, 'median' => 79.10, 'sd' => 2.23],
            ['gender' => 'laki-laki', 'usia_bulan' => 16, 'median' => 80.20, 'sd' => 2.24],
            ['gender' => 'laki-laki', 'usia_bulan' => 17, 'median' => 81.30, 'sd' => 2.25],
            ['gender' => 'laki-laki', 'usia_bulan' => 18, 'median' => 82.30, 'sd' => 2.26],
            ['gender' => 'laki-laki', 'usia_bulan' => 19, 'median' => 83.30, 'sd' => 2.27],
            ['gender' => 'laki-laki', 'usia_bulan' => 20, 'median' => 84.30, 'sd' => 2.28],
            ['gender' => 'laki-laki', 'usia_bulan' => 21, 'median' => 85.10, 'sd' => 2.29],
            ['gender' => 'laki-laki', 'usia_bulan' => 22, 'median' => 86.00, 'sd' => 2.30],
            ['gender' => 'laki-laki', 'usia_bulan' => 23, 'median' => 86.80, 'sd' => 2.32],
            ['gender' => 'laki-laki', 'usia_bulan' => 24, 'median' => 87.80, 'sd' => 2.33],
            ['gender' => 'laki-laki', 'usia_bulan' => 25, 'median' => 88.70, 'sd' => 2.34],
            ['gender' => 'laki-laki', 'usia_bulan' => 26, 'median' => 89.60, 'sd' => 2.35],
            ['gender' => 'laki-laki', 'usia_bulan' => 27, 'median' => 90.50, 'sd' => 2.36],
            ['gender' => 'laki-laki', 'usia_bulan' => 28, 'median' => 91.30, 'sd' => 2.38],
            ['gender' => 'laki-laki', 'usia_bulan' => 29, 'median' => 92.20, 'sd' => 2.39],
            ['gender' => 'laki-laki', 'usia_bulan' => 30, 'median' => 93.00, 'sd' => 2.40],
            ['gender' => 'laki-laki', 'usia_bulan' => 31, 'median' => 93.80, 'sd' => 2.41],
            ['gender' => 'laki-laki', 'usia_bulan' => 32, 'median' => 94.60, 'sd' => 2.42],
            ['gender' => 'laki-laki', 'usia_bulan' => 33, 'median' => 95.40, 'sd' => 2.44],
            ['gender' => 'laki-laki', 'usia_bulan' => 34, 'median' => 96.20, 'sd' => 2.45],
            ['gender' => 'laki-laki', 'usia_bulan' => 35, 'median' => 96.90, 'sd' => 2.46],
            ['gender' => 'laki-laki', 'usia_bulan' => 36, 'median' => 97.70, 'sd' => 2.47],
            ['gender' => 'laki-laki', 'usia_bulan' => 37, 'median' => 98.50, 'sd' => 2.48],
            ['gender' => 'laki-laki', 'usia_bulan' => 38, 'median' => 99.20, 'sd' => 2.49],
            ['gender' => 'laki-laki', 'usia_bulan' => 39, 'median' => 99.90, 'sd' => 2.50],
            ['gender' => 'laki-laki', 'usia_bulan' => 40, 'median' => 100.60, 'sd' => 2.51],
            ['gender' => 'laki-laki', 'usia_bulan' => 41, 'median' => 101.30, 'sd' => 2.52],
            ['gender' => 'laki-laki', 'usia_bulan' => 42, 'median' => 102.00, 'sd' => 2.53],
            ['gender' => 'laki-laki', 'usia_bulan' => 43, 'median' => 102.70, 'sd' => 2.54],
            ['gender' => 'laki-laki', 'usia_bulan' => 44, 'median' => 103.40, 'sd' => 2.55],
            ['gender' => 'laki-laki', 'usia_bulan' => 45, 'median' => 104.10, 'sd' => 2.56],
            ['gender' => 'laki-laki', 'usia_bulan' => 46, 'median' => 104.80, 'sd' => 2.57],
            ['gender' => 'laki-laki', 'usia_bulan' => 47, 'median' => 105.50, 'sd' => 2.58],
            ['gender' => 'laki-laki', 'usia_bulan' => 48, 'median' => 106.10, 'sd' => 2.59],
            ['gender' => 'laki-laki', 'usia_bulan' => 49, 'median' => 106.80, 'sd' => 2.60],
            ['gender' => 'laki-laki', 'usia_bulan' => 50, 'median' => 107.40, 'sd' => 2.61],
            ['gender' => 'laki-laki', 'usia_bulan' => 51, 'median' => 108.00, 'sd' => 2.62],
            ['gender' => 'laki-laki', 'usia_bulan' => 52, 'median' => 108.60, 'sd' => 2.63],
            ['gender' => 'laki-laki', 'usia_bulan' => 53, 'median' => 109.20, 'sd' => 2.64],
            ['gender' => 'laki-laki', 'usia_bulan' => 54, 'median' => 109.80, 'sd' => 2.65],
            ['gender' => 'laki-laki', 'usia_bulan' => 55, 'median' => 110.40, 'sd' => 2.66],
            ['gender' => 'laki-laki', 'usia_bulan' => 56, 'median' => 111.00, 'sd' => 2.67],
            ['gender' => 'laki-laki', 'usia_bulan' => 57, 'median' => 111.50, 'sd' => 2.68],
            ['gender' => 'laki-laki', 'usia_bulan' => 58, 'median' => 112.10, 'sd' => 2.69],
            ['gender' => 'laki-laki', 'usia_bulan' => 59, 'median' => 112.60, 'sd' => 2.70],
            ['gender' => 'laki-laki', 'usia_bulan' => 60, 'median' => 113.00, 'sd' => 2.71],

            // Perempuan (WHO)
            // Perempuan (WHO)
            ['gender' => 'perempuan', 'usia_bulan' => 0, 'median' => 49.15, 'sd' => 1.89],
            ['gender' => 'perempuan', 'usia_bulan' => 1, 'median' => 53.69, 'sd' => 1.97],
            ['gender' => 'perempuan', 'usia_bulan' => 2, 'median' => 57.07, 'sd' => 2.02],
            ['gender' => 'perempuan', 'usia_bulan' => 3, 'median' => 59.80, 'sd' => 2.04],
            ['gender' => 'perempuan', 'usia_bulan' => 4, 'median' => 62.10, 'sd' => 2.06],
            ['gender' => 'perempuan', 'usia_bulan' => 5, 'median' => 64.00, 'sd' => 2.08],
            ['gender' => 'perempuan', 'usia_bulan' => 6, 'median' => 65.60, 'sd' => 2.09],
            ['gender' => 'perempuan', 'usia_bulan' => 7, 'median' => 67.10, 'sd' => 2.11],
            ['gender' => 'perempuan', 'usia_bulan' => 8, 'median' => 68.50, 'sd' => 2.13],
            ['gender' => 'perempuan', 'usia_bulan' => 9, 'median' => 69.80, 'sd' => 2.15],
            ['gender' => 'perempuan', 'usia_bulan' => 10, 'median' => 71.00, 'sd' => 2.17],
            ['gender' => 'perempuan', 'usia_bulan' => 11, 'median' => 72.20, 'sd' => 2.18],
            ['gender' => 'perempuan', 'usia_bulan' => 12, 'median' => 73.40, 'sd' => 2.20],
            ['gender' => 'perempuan', 'usia_bulan' => 13, 'median' => 74.50, 'sd' => 2.21],
            ['gender' => 'perempuan', 'usia_bulan' => 14, 'median' => 75.60, 'sd' => 2.22],
            ['gender' => 'perempuan', 'usia_bulan' => 15, 'median' => 76.70, 'sd' => 2.23],
            ['gender' => 'perempuan', 'usia_bulan' => 16, 'median' => 77.80, 'sd' => 2.24],
            ['gender' => 'perempuan', 'usia_bulan' => 17, 'median' => 78.80, 'sd' => 2.25],
            ['gender' => 'perempuan', 'usia_bulan' => 18, 'median' => 79.80, 'sd' => 2.26],
            ['gender' => 'perempuan', 'usia_bulan' => 19, 'median' => 80.80, 'sd' => 2.27],
            ['gender' => 'perempuan', 'usia_bulan' => 20, 'median' => 81.70, 'sd' => 2.28],
            ['gender' => 'perempuan', 'usia_bulan' => 21, 'median' => 82.60, 'sd' => 2.29],
            ['gender' => 'perempuan', 'usia_bulan' => 22, 'median' => 83.50, 'sd' => 2.30],
            ['gender' => 'perempuan', 'usia_bulan' => 23, 'median' => 84.30, 'sd' => 2.31],
            ['gender' => 'perempuan', 'usia_bulan' => 24, 'median' => 85.10, 'sd' => 2.32],
            ['gender' => 'perempuan', 'usia_bulan' => 25, 'median' => 85.90, 'sd' => 2.33],
            ['gender' => 'perempuan', 'usia_bulan' => 26, 'median' => 86.60, 'sd' => 2.34],
            ['gender' => 'perempuan', 'usia_bulan' => 27, 'median' => 87.40, 'sd' => 2.35],
            ['gender' => 'perempuan', 'usia_bulan' => 28, 'median' => 88.10, 'sd' => 2.36],
            ['gender' => 'perempuan', 'usia_bulan' => 29, 'median' => 88.90, 'sd' => 2.37],
            ['gender' => 'perempuan', 'usia_bulan' => 30, 'median' => 89.60, 'sd' => 2.38],
            ['gender' => 'perempuan', 'usia_bulan' => 31, 'median' => 90.30, 'sd' => 2.39],
            ['gender' => 'perempuan', 'usia_bulan' => 32, 'median' => 91.00, 'sd' => 2.40],
            ['gender' => 'perempuan', 'usia_bulan' => 33, 'median' => 91.70, 'sd' => 2.41],
            ['gender' => 'perempuan', 'usia_bulan' => 34, 'median' => 92.40, 'sd' => 2.42],
            ['gender' => 'perempuan', 'usia_bulan' => 35, 'median' => 93.10, 'sd' => 2.43],
            ['gender' => 'perempuan', 'usia_bulan' => 36, 'median' => 93.80, 'sd' => 2.44],
            ['gender' => 'perempuan', 'usia_bulan' => 37, 'median' => 94.50, 'sd' => 2.45],
            ['gender' => 'perempuan', 'usia_bulan' => 38, 'median' => 95.20, 'sd' => 2.46],
            ['gender' => 'perempuan', 'usia_bulan' => 39, 'median' => 95.90, 'sd' => 2.47],
            ['gender' => 'perempuan', 'usia_bulan' => 40, 'median' => 96.50, 'sd' => 2.48],
            ['gender' => 'perempuan', 'usia_bulan' => 41, 'median' => 97.20, 'sd' => 2.49],
            ['gender' => 'perempuan', 'usia_bulan' => 42, 'median' => 97.90, 'sd' => 2.50],
            ['gender' => 'perempuan', 'usia_bulan' => 43, 'median' => 98.50, 'sd' => 2.51],
            ['gender' => 'perempuan', 'usia_bulan' => 44, 'median' => 99.20, 'sd' => 2.52],
            ['gender' => 'perempuan', 'usia_bulan' => 45, 'median' => 99.80, 'sd' => 2.53],
            ['gender' => 'perempuan', 'usia_bulan' => 46, 'median' => 100.40, 'sd' => 2.54],
            ['gender' => 'perempuan', 'usia_bulan' => 47, 'median' => 101.00, 'sd' => 2.55],
            ['gender' => 'perempuan', 'usia_bulan' => 48, 'median' => 101.70, 'sd' => 2.56],
            ['gender' => 'perempuan', 'usia_bulan' => 49, 'median' => 102.30, 'sd' => 2.57],
            ['gender' => 'perempuan', 'usia_bulan' => 50, 'median' => 102.90, 'sd' => 2.58],
            ['gender' => 'perempuan', 'usia_bulan' => 51, 'median' => 103.50, 'sd' => 2.59],
            ['gender' => 'perempuan', 'usia_bulan' => 52, 'median' => 104.10, 'sd' => 2.60],
            ['gender' => 'perempuan', 'usia_bulan' => 53, 'median' => 104.70, 'sd' => 2.61],
            ['gender' => 'perempuan', 'usia_bulan' => 54, 'median' => 105.30, 'sd' => 2.62],
            ['gender' => 'perempuan', 'usia_bulan' => 55, 'median' => 105.90, 'sd' => 2.63],
            ['gender' => 'perempuan', 'usia_bulan' => 56, 'median' => 106.50, 'sd' => 2.64],
            ['gender' => 'perempuan', 'usia_bulan' => 57, 'median' => 107.10, 'sd' => 2.65],
            ['gender' => 'perempuan', 'usia_bulan' => 58, 'median' => 107.70, 'sd' => 2.66],
            ['gender' => 'perempuan', 'usia_bulan' => 59, 'median' => 108.50, 'sd' => 2.67],
            ['gender' => 'perempuan', 'usia_bulan' => 60, 'median' => 111.30, 'sd' => 2.67],

        ];

        DB::table('ref_tb_u')->insert($data);
    }
}
